### ISSUE TITLE
Worflow items to add from HextofProcessor

### ISSUE THREAD

**Issue by rettigl** [OpenCOMPES/sed#167]
These workflow items should be added as discussed today:

- [x] Sector calibration for the 8-sector DLD. I suggest to split this up into parameter generation and application function, similar as done for the other calibration/correction functions, and perform the operation on the digitized DLD bin coordinates, rather than converted ns coordinates (for compatibility with the current jitter framework, see #163)

- [x] Funtion to shift the energy axis. This could include photon energy, bias voltage, a given, external offset, and potentially any other voltages that influence the energy scale. We could also place the code that swaps the energy axis from kinetic to binding energy scale here.
- [x] #236
- [x] #237
- [x] Add default jitter columns to the default config, that refer to the config names of the X, Y, TOF columns

**Comment by rettigl** [comment]
> 
>     * [x]  Add default jitter columns to the default config, that refer to the config names of the X, Y, TOF columns

The last point is addressed in PR #168

**Comment by steinnymir** [comment]
> Funtion to shift the energy axis. This could include photon energy, bias voltage, a given, external offset, and potentially any other voltages that influence the energy scale. We could also place the code that swaps the energy axis from kinetic to binding energy scale here.

addressed in #169

**Comment by steinnymir** [comment]
> Sector calibration for the 8-sector DLD. I suggest to split this up into parameter generation and application function, similar as done for the other calibration/correction functions, and perform the operation on the digitized DLD bin coordinates, rather than converted ns coordinates (for compatibility with the current jitter framework, see https://github.com/OpenCOMPES/sed/issues/163)

correction implemented in #169. Parameter generation still missing

**Comment by steinnymir** [comment]
all tasks completed
